# version: '3.8'
services:

  db:
    build: ./db
    container_name: tripin_db
    networks:
      - tripin_net
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis
    container_name: tripin_redis
    networks:
      - tripin_net
    ports:
      - "8993:6379"
    volumes:
      - redisdata:/data
  flask:
    container_name: tripin_server
    networks:
      - tripin_net
    build: .
    ports:
      - "8992:8000"
      - "1514:1514"
    environment:
      - LOGDIR=logs
      - ERRORLOGDIR=logs/errorlogs
    env_file:
      - src/assets/configs/.env
      - .env
    depends_on:
      - db
      - redis
    volumes:
      - ./src/assets:/app/src/assets
  # logs:
  #   image: 2axxaxx/nginx_logs:latest
  #   ports:
  #     - '12345:12345/udp'
  #   env_file:
  #     - '.env'
  #   environment:
  #     - LOG_DIR=/app/logs
  #   volumes:
  #     - ./logs:/app/logs
volumes:
  pgdata:
  redisdata:


networks:
  tripin_net:
    external: true

# version: '3.8'
