# version: '3.8'
services:
  test_db:
    image: postgres:15
    # container_name: test_tripin_db
    environment:
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpass
      POSTGRES_DB: tripin
    ports:
      - "5435:5432"
    tmpfs:
      - /var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U testuser -d tripin"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s

  test_redis:
    image: redis
    # container_name: test_tripin_redis
    ports:
      - "8995:6379"
    tmpfs:
      - /data

  test_server:
    # container_name: test_tripin_server
    build: .
    ports:
      - "8985:8000"
      - "1515:1514"
    env_file:
      - .env.test
    depends_on:
      test_db:
        condition: service_healthy
    volumes:
      - ./src/assets/keys:/app/src/assets/keys
    command: >
      sh -c "
              echo 'migration database' &&
              alembic upgrade head &&
              echo 'create test user'&&
              python tests/scripts/create_test_user.py &&
              echo 'pytest version' &&
              pytest --version &&
              echo 'wait' &&
              sleep 10 &&
              echo 'run test'&&
              python -m pytest -p no:all --collect-only -vv &&
    restart: "no"
