from types import SimpleNamespace

DATABASEKEYS = SimpleNamespace(
    TABLES=SimpleNamespace(
        USERDATA="tripin_auth.userdata",
        TOKENS="tripin_auth.tokens",
        TRIP_COORDINATES="tripin_trips.trip_coordinates",
        TRIP_MEDIAS="tripin_trips.trip_medias",
        TRIPS="tripin_trips.trips_table",
        TRIP_SHARED_LINKS="tripin_trips.trip_shared_links",
        USER_AUDIT="tripin_auth.user_audit",
        TRIP_CONTENT_CARDS="tripin_trips.content_cards",
        USER_SETTINGS="tripin_auth.user_settings",
        FRIENDSHIPS="tripin_friendships.friendships_table",
        DEVICES ="tripin_auth.devices"
    ),
    USERDATA=SimpleNamespace(
        USER_ID="id",
        EMAIL="email",
        DISPLAY_NAME="display_name",
        USER_NAME="user_name",
        PASSWORD="password",
        CREATED_TIME="created_time",
        ROLE="role",
        AVARTAR="avatar",
        ETAG="etag",
        # TRIPS_DATA_VERSION='trips_data_version',
        # TRIPS_DATA_ETAG ='trips_data_etag',
        # USER_DATA_VERSION ='userdata_version',
        PROVIDER="provider",
        PROVIDER_ID="provider_id",
        MODIFIED_TIME="modified_time",
        TRIPS_MODIFIED_TIME="trips_modified_time",
    ),
    TOKENS=SimpleNamespace(
        TOKEN_ID="id",
        USER_ID="user_id",
        # USER_NAME="user_name",
        TOKEN="token",
        ISSUE_TIME="issued_at",
        EXPIRED_TIME="expired_at",
        REVOKED="revoked",
        DEVICE_ID="device_id",
        LAST_USED="last_used",
    ),
    TRIPS=SimpleNamespace(
        TRIP_ID="id",
        USER_ID="user_id",
        CREATED_TIME="created_time",
        ACTIVE="active",
        ENDED_TIME="ended_time",
        TRIP_NAME="trip_name",
        IMAGE_KEY="image",
        # TRIP_ETAG="etag",
        # TRIP_INFO_VERSION="trip_informations_version",
        # TRIP_COORDINATES_VERSION="trip_coordinates_version",
        # TRIPS_MEDIAS_VERSION="trip_medias_version",
        MODIFIED_TIME="modified_time",
        CONTENT_MODIFIED_TIME="content_modified_time",
        EVENT="event",
        PRIVACY = 'privacy'
    ),
    TRIP_MEDIAS=SimpleNamespace(
        # MEDIA_ID ='id',
        TRIP_ID="trip_id",
        MEDIA_TYPE="media_type",
        MEDIA_PATH="media_path",
        KEY="key",
        LONGITUDE="longitude",
        LATITUDE="latitude",
        TIME_STAMP="time_stamp",
        VERSION="version",
        MODIFIED_TIME="modified_time",
        IS_DELETED="is_deleted",
        MEDIA_ID="media_id",
        COORDINATE_ID="coordinate_id",
        EVENT="event",
        CITY="city",
        REGION="region",
        COUNTRY="country",
        ISO_COUNTRY_CODE="iso_country_code",
    ),
    TRIP_COORDINATES=SimpleNamespace(
        COORDINATES_ID="id",
        TRIP_ID="trip_id",
        BATCH_VERSION="batch_version",
        LONGITUDE="longitude",
        LATITUDE="latitude",
        ALTITUDE="altitude",
        SPEED="speed",
        HEADING="heading",
        TIME_STAMP="time_stamp",
        COORDINATE_ID="coordinate_id",
        EVENT="event",
        MODIFIED_TIME="modified_time",
    ),
    TRIP_CONTENT_CARDS=SimpleNamespace(
        CARD_ID="id",
        TRIP_ID="trip_id",
        LONGITUDE="longitude",
        LATITUDE="latitude",
        ALTITUDE="altitude",
        SPEED="speed",
        HEADING="heading",
        TIME_STAMP="time_stamp",
        MODIFIED_TIME="modified_time",
        MEDIA_ID="media_id",
        MEDIA_TYPE="media_type",
        MEDIA_PATH="media_path",
        UUID="uuid",
        EVENT="event",
        CITY="city",
        REGION="region",
        COUNTRY="country",
        ISO_COUNTRY_CODE="iso_country_code",
    ),
    TRIP_SHARED_LINKS=SimpleNamespace(
        LINKS_ID="id",
        USER_ID="user_id",
        TRIP_ID="trip_id",
        CREATED_TIME="created_time",
        EXPIRED_TIME="expired_time",
        REVOKE="revoke",
        VISIBILITY="visibility",
        TOKEN="token",
    ),
    USER_AUDIT=SimpleNamespace(
        ID="id",
        USER_ID="user_id",
        MODIFIED_TIME="modified_time",
        ACTION="action",
        IP_ADDRESS="ip_address",
        NEW_VALUE="new_value",
        OLD_VALUE="old_value",
    ),
    USER_SETTINGS=SimpleNamespace(
        USER_ID="user_id",
        HAS_SEEN_ONBOARDING="has_seen_onboarding",
        LANGUAGE="language",
        UPDATE_AT="update_at",
    ),
    FRIENDSHIPS=SimpleNamespace(
        USER_ID1="user_id1",
        USER_ID2="user_id2",
        STATUS="status",
        LAST_UPDATE="last_update",
    ),
    DEVICES = SimpleNamespace(
        ID="id",
        USER_ID="user_id",
        DEVICE_ID="device_id",
        TOKEN="token",
        PLATFORM="platform",
        LAST_SEEN="last_seen",
    )
)
