name: Tripping Server Deploy

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    uses: ./.github/workflows/test.yml
    secrets:
      PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
      PUBLIC_KEY: ${{ secrets.PUBLIC_KEY }}
      ENV_TEST_BASE_64: ${{ secrets.ENV_TEST_BASE_64 }}
  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' # only deploy on push to main, not PRs
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd tripin_server
            git fetch origin main
            git reset --hard origin/main
            mkdir -p ./logs/errorlogs
            docker image prune -f
