name: Tripping Server Test

on:
  workflow_call:
    secrets:
      PRIVATE_KEY:
        required: true
      PUBLIC_KEY:
        required: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set Up and Run Tests
        run: |
          docker compose -f docker-compose.test.yml --env-file .env.test up \
          --build \
          --abort-on-container-exit \
          --exit-code-from server_test

      - name: Clean Up
        if: always()
        run: docker compose -f docker-compose.test.yml down -v